name: Release CI
on:
  push:
    branches:
    - nau/*.master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Nodejs Env
      run: echo "NODE_VER=`cat .nvmrc`" >> $GITHUB_ENV
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VER }}
    - name: Install dependencies
      run: npm ci
    - name: Validate package-lock.json changes
      run: make validate-no-uncommitted-package-lock-changes
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test
    - name: i18n_extract
      run: npm run i18n_extract
    - name: Coverage
      uses: codecov/codecov-action@v3
    - name: Build
      run: npm run build
    - name: Release to npmjs
      uses: pascalgn/npm-publish-action@1.3.9
      with:
        tag_name: "v%s"
        tag_message: "v%s"
        commit_pattern: "^chore(release): (\\S+)"
        workspace: "."
        publish_command: "npm"
        publish_args: "--non-interactive"
      env:
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}
